import React, { useState, useId } from 'react';
import { LANG } from './i18n.js';
import { SolutionArt } from './solution-art.jsx';
import './styles/experience-pages.css';

const COPY = {
  pt: {
    solutions:['SOLUÇÕES / WIR','O seu conhecimento.','Uma nova escala.','Distribuição, subscrição e visibilidade. Três capacidades conectadas para ampliar o que sua equipe consegue fazer.','Explorar as soluções','Conhecer o caminho'],
    names:['Distribuição','Subscrição','Visibilidade'],
    overview:['Um sistema conectado.','Mais possibilidades.','Cada operação tem uma prioridade. O ponto de partida é o seu negócio.'],
    benefits:['Encontre e priorize oportunidades com mais contexto.','Transforme informações em análises com critério.','Enxergue processos e acompanhe sua operação.'],
    productIntro:['POR DENTRO DAS SOLUÇÕES','Da oportunidade','à decisão.','Explore as capacidades de cada produto e onde elas entram na sua operação.'],
    visibility:['CLAREZA PARA DECIDIR','A operação inteira.','Uma visão conectada.','Dashboards e analytics ajudam sua equipe a acompanhar processos, reconhecer prioridades e orientar decisões.','Explore também o mercado','O dashboard público da WIR reúne dados SUSEP sobre o mercado segurador brasileiro. Consulte períodos, ramos e grupos seguradores.','Abrir Dashboard SUSEP'],
    how:['COMO FUNCIONA / WIR','O trabalho chega.','A capacidade cresce.','Dos e-mails que chegam todos os dias a uma operação mais conectada. A IA organiza a informação; sua equipe orienta as decisões.','Explore o fluxo'],
    flowKicker:'DA INFORMAÇÃO À AÇÃO', flowTitle:['Tudo começa com','o que já chega.'],
    phases:[['Receber','E-mails, anexos e solicitações entram no fluxo da operação.','O contexto começa aqui.'],['Conectar','A informação é organizada e conectada aos critérios do negócio.','Dados com contexto.'],['Agir','As análises apoiam o trabalho da equipe e o acompanhamento da operação.','Mais clareza para o próximo passo.']],
    mail:['Cotação','Consulta','Acompanhamento'], illustration:'Fluxo conceitual · não representa uma tela do produto',
    implementation:['DA PRIORIDADE À OPERAÇÃO','Um caminho construído','com a sua equipe.','Tecnologia, conhecimento do negócio e acompanhamento em cada etapa.'],
    steps:[['Diagnóstico','Entendemos antes de configurar.','Mapeamos seus objetivos, o contexto da operação e as informações que chegam.','Prioridades do negócio','Fluxos e pontos de atenção','Escopo da solução'],['Implementação','Conectamos ao seu contexto.','Configuramos a solução, integramos o fluxo e preparamos a equipe para o uso.','Configuração e integração','Testes e ajustes','Preparação da equipe'],['Operação','Evoluímos junto com o uso.','Acompanhamos a operação, apoiamos a equipe e identificamos oportunidades de evolução.','Acompanhamento próximo','Suporte ao uso','Evolução contínua']],
    human:['A IA organiza.','A experiência decide.','Critérios de negócio, contexto e revisão humana fazem parte da conversa desde o início.','Conheça quem está por trás'],
    about:['SOBRE A WIR','Experiência que entende.','Tecnologia que amplia.','Conhecemos os desafios de seguros por dentro. Conectamos essa experiência à IA para construir mais capacidade com a sua equipe.','Conheça o time'],
    belief:['WIR significa','nós.','Pessoas, conhecimento e tecnologia trabalhando na mesma direção.','Seguros','Negócios','Tecnologia'],
    close:['O próximo capítulo','começa com você.','Conte o que é prioridade para sua operação. Vamos explorar o caminho juntos.','Falar com a WIR'],
  },
  en: {
    solutions:['SOLUTIONS / WIR','Your expertise.','A new scale.','Distribution, underwriting and visibility. Three connected capabilities to expand what your team can do.','Explore the solutions','See how it works'],
    names:['Distribution','Underwriting','Visibility'],overview:['One connected system.','More possibilities.','Every operation has a priority. Your business is the starting point.'],
    benefits:['Find and prioritize opportunities with more context.','Turn information into analysis with consistent criteria.','See processes clearly and monitor your operation.'],
    productIntro:['INSIDE THE SOLUTIONS','From opportunity','to decision.','Explore each product’s capabilities and where they fit into your operation.'],
    visibility:['CLARITY FOR DECISIONS','The whole operation.','One connected view.','Dashboards and analytics help your team monitor processes, recognize priorities and guide decisions.','Explore the market too','WIR’s public dashboard brings together SUSEP data on the Brazilian insurance market. Explore periods, business lines and insurance groups.','Open SUSEP Dashboard'],
    how:['HOW IT WORKS / WIR','Work comes in.','Capacity grows.','From the emails arriving every day to a more connected operation. AI organizes information; your team guides the decisions.','Explore the flow'],
    flowKicker:'FROM INFORMATION TO ACTION',flowTitle:['It starts with','what already arrives.'],
    phases:[['Receive','Emails, attachments and requests enter the operational workflow.','Context starts here.'],['Connect','Information is organized and connected to business criteria.','Data with context.'],['Act','Analysis supports the team’s work and operational monitoring.','Clarity for the next step.']],
    mail:['Quotation','Inquiry','Follow-up'],illustration:'Conceptual flow · not a product screenshot',
    implementation:['FROM PRIORITIES TO OPERATION','A path built','with your team.','Technology, business knowledge and support at every stage.'],
    steps:[['Diagnosis','Understand before configuring.','We map your objectives, operational context and incoming information.','Business priorities','Workflows and challenges','Solution scope'],['Implementation','Connect to your context.','We configure the solution, integrate the workflow and prepare your team.','Configuration and integration','Testing and adjustments','Team preparation'],['Operation','Evolve through everyday use.','We follow the operation, support your team and identify opportunities to improve.','Close follow-up','Support for adoption','Continuous improvement']],
    human:['AI organizes.','Experience decides.','Business criteria, context and human review are part of the conversation from the start.','Meet the people behind WIR'],
    about:['ABOUT WIR','Experience that understands.','Technology that expands.','We know insurance challenges from the inside. We connect that experience with AI to build more capacity alongside your team.','Meet the team'],
    belief:['WIR means','we.','People, knowledge and technology working in the same direction.','Insurance','Business','Technology'],
    close:['The next chapter','starts with you.','Tell us what matters most to your operation. Let’s explore the path together.','Talk to WIR'],
  },
  es: {
    solutions:['SOLUCIONES / WIR','Tu conocimiento.','Una nueva escala.','Distribución, suscripción y visibilidad. Tres capacidades conectadas para ampliar lo que tu equipo puede hacer.','Explorar las soluciones','Conocer el camino'],
    names:['Distribución','Suscripción','Visibilidad'],overview:['Un sistema conectado.','Más posibilidades.','Cada operación tiene una prioridad. El punto de partida es tu negocio.'],
    benefits:['Encuentra y prioriza oportunidades con más contexto.','Transforma información en análisis con criterio.','Visualiza los procesos y sigue tu operación.'],
    productIntro:['DENTRO DE LAS SOLUCIONES','De la oportunidad','a la decisión.','Explora las capacidades de cada producto y dónde encajan en tu operación.'],
    visibility:['CLARIDAD PARA DECIDIR','Toda la operación.','Una visión conectada.','Dashboards y analytics ayudan a tu equipo a seguir procesos, reconocer prioridades y orientar decisiones.','Explora también el mercado','El dashboard público de WIR reúne datos SUSEP del mercado asegurador brasileño. Consulta períodos, ramos y grupos aseguradores.','Abrir Dashboard SUSEP'],
    how:['CÓMO FUNCIONA / WIR','El trabajo llega.','La capacidad crece.','De los mails que llegan cada día a una operación más conectada. La IA organiza la información; tu equipo orienta las decisiones.','Explorar el flujo'],
    flowKicker:'DE LA INFORMACIÓN A LA ACCIÓN',flowTitle:['Todo empieza con','lo que ya llega.'],
    phases:[['Recibir','Mails, adjuntos y solicitudes entran al flujo de la operación.','El contexto comienza aquí.'],['Conectar','La información se organiza y conecta con los criterios del negocio.','Datos con contexto.'],['Actuar','Los análisis apoyan el trabajo del equipo y el seguimiento de la operación.','Claridad para el próximo paso.']],
    mail:['Cotización','Consulta','Seguimiento'],illustration:'Flujo conceptual · no representa una pantalla del producto',
    implementation:['DE LA PRIORIDAD A LA OPERACIÓN','Un camino construido','con tu equipo.','Tecnología, conocimiento del negocio y acompañamiento en cada etapa.'],
    steps:[['Diagnóstico','Entender antes de configurar.','Mapeamos tus objetivos, el contexto operativo y la información que llega.','Prioridades del negocio','Flujos y puntos de atención','Alcance de la solución'],['Implementación','Conectamos con tu contexto.','Configuramos la solución, integramos el flujo y preparamos al equipo.','Configuración e integración','Pruebas y ajustes','Preparación del equipo'],['Operación','Evolucionamos con el uso.','Acompañamos la operación, apoyamos al equipo e identificamos oportunidades de mejora.','Acompañamiento cercano','Apoyo al uso','Evolución continua']],
    human:['La IA organiza.','La experiencia decide.','Los criterios del negocio, el contexto y la revisión humana forman parte de la conversación desde el inicio.','Conoce quiénes están detrás'],
    about:['SOBRE WIR','Experiencia que entiende.','Tecnología que amplía.','Conocemos los desafíos de seguros desde adentro. Conectamos esa experiencia con IA para construir más capacidad junto a tu equipo.','Conoce al equipo'],
    belief:['WIR significa','nosotros.','Personas, conocimiento y tecnología trabajando en la misma dirección.','Seguros','Negocios','Tecnología'],
    close:['El próximo capítulo','comienza contigo.','Cuéntanos qué es prioridad para tu operación. Exploremos el camino juntos.','Hablar con WIR'],
  },
};
const T = COPY[LANG];
export function ExperienceLink({go,route='contact',anchor,children,secondary=false}) {
  return <a className={'xp-button'+(secondary?' xp-button--secondary':'')} href={'#'+route+(anchor?'#'+anchor:'')} onClick={e=>{e.preventDefault();go(route,anchor);}}>{children}<span aria-hidden="true">↗</span></a>;
}
function LightThreads() {
  const id=useId().replace(/:/g,'');
  return <svg className="xp-threads" viewBox="0 0 700 520" fill="none" aria-hidden="true"><defs><linearGradient id={id}><stop stopColor="#f8ad39"/><stop offset=".5" stopColor="#b898ff"/><stop offset="1" stopColor="#5047ff"/></linearGradient><filter id={id+'g'}><feGaussianBlur stdDeviation="6"/></filter></defs>{[0,1,2,3,4,5].map(i=><g key={i}><path d={`M-40 ${410+i*5} C 200 ${470-i*7}, 160 ${170+i*12}, 340 260 S 490 ${160+i*40}, 750 ${60+i*72}`} stroke={'url(#'+id+')'} strokeWidth="5" opacity=".3" filter={'url(#'+id+'g)'}/><path d={`M-40 ${410+i*5} C 200 ${470-i*7}, 160 ${170+i*12}, 340 260 S 490 ${160+i*40}, 750 ${60+i*72}`} stroke={'url(#'+id+')'} strokeWidth="1.1" opacity={1-i*.1}/></g>)}</svg>;
}
function GlassSystem({flow=false,phase=2}) {
  return <div className={'xp-sculpture'+(flow?' xp-sculpture--flow xp-sculpture--phase-'+phase:'')} aria-hidden="true"><div className="xp-scene-halo"/><LightThreads/><div className="xp-floor"/>
    {flow?<><div className="xp-mail-stack">{T.mail.map((mail,i)=><div className="xp-mail" key={mail} style={{'--i':i}}><span className="xp-envelope"/><span>{mail}</span><i/></div>)}</div><div className={'xp-core xp-core--'+phase}><span>WIR</span><i/><i/><i/></div><div className="xp-output">{T.names.map((n,i)=><span key={n} style={{'--i':i}}><i/>{n}</span>)}</div></>:<div className="xp-glass-system">{T.names.map((n,i)=><div className="xp-glass" key={n} style={{'--i':i}}><span className="xp-glass__number">0{i+1}</span><div className={'xp-glyph xp-glyph--'+i}>{[0,1,2,3].map(k=><i key={k}/>)}</div><span className="xp-glass__label">{n}</span></div>)}</div>}
  </div>;
}
function SectionHeading({kicker,first,second,note}) {return <div className="xp-section-head"><div><p className="xp-kicker">{kicker}</p><h2 className="xp-title">{first}<br/><em>{second}</em></h2></div>{note&&<p>{note}</p>}</div>;}
export function ExperienceClose({go}) {return <section className="xp-close"><LightThreads/><div className="xp-wrap"><p className="xp-kicker">WIR / AI FOR INSURANCE</p><h2 className="xp-title">{T.close[0]}<br/><em>{T.close[1]}</em></h2><p>{T.close[2]}</p><ExperienceLink go={go}>{T.close[3]}</ExperienceLink></div></section>;}
export function SolutionsExperience({go,children}) {
 return <div className="experience-page experience-solutions">
  <section className="xp-hero"><div className="xp-wrap xp-hero__grid"><div className="xp-hero__copy"><p className="xp-kicker">{T.solutions[0]}</p><h1 className="xp-title">{T.solutions[1]}<br/><em>{T.solutions[2]}</em></h1><p className="xp-lede">{T.solutions[3]}</p><div className="xp-actions"><ExperienceLink go={go} route="solutions" anchor="solution-overview">{T.solutions[4]}</ExperienceLink><ExperienceLink go={go} route="how" secondary>{T.solutions[5]}</ExperienceLink></div></div><GlassSystem/></div><div className="xp-hero__caption">01 — 03 <span>WIR / AI SCALE SOLUTIONS</span></div></section>
  <section className="xp-overview" id="solution-overview"><div className="xp-wrap"><SectionHeading kicker="01 / AI SCALE SOLUTIONS" first={T.overview[0]} second={T.overview[1]} note={T.overview[2]}/><div className="xp-capability-list">{T.names.map((name,i)=><a key={name} href={'#solutions#'+['stack-tab-SS','stack-tab-UI','operational-intelligence'][i]} onClick={e=>{e.preventDefault();go('solutions',['stack-tab-SS','stack-tab-UI','operational-intelligence'][i]);}}><span className="xp-index">0{i+1}</span><SolutionArt compact kind={['SS','UI','analytics'][i]}/><h3>{name}<small>{['Smart Sales','Underwriter Intelligence','Dashboards & analytics'][i]}</small></h3><p>{T.benefits[i]}</p><span className="xp-list-arrow" aria-hidden>↗</span></a>)}</div></div></section>
  <section className="xp-product-heading"><div className="xp-wrap"><SectionHeading kicker={T.productIntro[0]} first={T.productIntro[1]} second={T.productIntro[2]} note={T.productIntro[3]}/></div></section>
  <div className="xp-products">{children}</div>
  <section className="xp-visibility" id="operational-intelligence"><div className="xp-wrap xp-visibility__grid"><div><p className="xp-kicker">03 / {T.visibility[0]}</p><h2 className="xp-title">{T.visibility[1]}<br/><em>{T.visibility[2]}</em></h2><p className="xp-lede">{T.visibility[3]}</p></div><SolutionArt kind="analytics"/><a className="xp-market-link" href={'/dashboard/?lang='+LANG}><div><span className="xp-kicker">DASHBOARD SUSEP / BRASIL</span><h3>{T.visibility[4]}</h3><p>{T.visibility[5]}</p></div><span>{T.visibility[6]} ↗</span></a></div></section>
  <section className="xp-bridge"><div className="xp-wrap"><div><p className="xp-kicker">{T.implementation[0]}</p><h2 className="xp-title">{T.implementation[1]}<br/><em>{T.implementation[2]}</em></h2></div><ExperienceLink go={go} route="how">{T.solutions[5]}</ExperienceLink></div></section><ExperienceClose go={go}/>
 </div>;
}
export function HowPage({go}) {
 const [phase,setPhase]=useState(0);
 const onKey=e=>{const keys={ArrowRight:(phase+1)%3,ArrowLeft:(phase+2)%3,Home:0,End:2};if(keys[e.key]!==undefined){e.preventDefault();setPhase(keys[e.key]);document.getElementById('flow-tab-'+keys[e.key])?.focus();}};
 return <div className="experience-page experience-how"><section className="xp-hero xp-hero--how"><div className="xp-wrap xp-hero__grid"><div className="xp-hero__copy"><p className="xp-kicker">{T.how[0]}</p><h1 className="xp-title">{T.how[1]}<br/><em>{T.how[2]}</em></h1><p className="xp-lede">{T.how[3]}</p><ExperienceLink go={go} route="how" anchor="information-flow">{T.how[4]}</ExperienceLink></div><GlassSystem flow/></div></section>
 <section className="xp-flow" id="information-flow"><div className="xp-wrap"><SectionHeading kicker={T.flowKicker} first={T.flowTitle[0]} second={T.flowTitle[1]}/><div className="xp-flow-tabs" role="tablist" aria-label={T.flowKicker}>{T.phases.map((p,i)=><button id={'flow-tab-'+i} key={p[0]} role="tab" aria-selected={phase===i} aria-controls="flow-panel" tabIndex={phase===i?0:-1} onClick={()=>setPhase(i)} onKeyDown={onKey}><span>0{i+1}</span>{p[0]}<i aria-hidden>→</i></button>)}</div><div className="xp-flow-panel" id="flow-panel" role="tabpanel" aria-labelledby={'flow-tab-'+phase} tabIndex={0}><div key={phase} className="xp-flow-detail"><span className="xp-index">0{phase+1}</span><h3>{T.phases[phase][2]}</h3><p>{T.phases[phase][1]}</p></div><GlassSystem flow phase={phase}/><small>{T.illustration}</small></div></div></section>
 <section className="xp-implementation" id="implementation"><div className="xp-wrap"><SectionHeading kicker={T.implementation[0]} first={T.implementation[1]} second={T.implementation[2]} note={T.implementation[3]}/><div className="xp-process">{T.steps.map((step,i)=><article key={step[0]}><div className="xp-process__top"><span>0{i+1}</span><div className={'xp-step-shape xp-step-shape--'+i}><i/><i/><i/></div></div><p className="xp-kicker">{step[0]}</p><h3>{step[1]}</h3><p>{step[2]}</p><ul>{step.slice(3).map(s=><li key={s}>{s}</li>)}</ul></article>)}</div></div></section>
 <section className="xp-human"><div className="xp-wrap"><div className="xp-human-mark" aria-hidden="true"><span>AI</span><b>+</b><span>WIR</span></div><div><h2 className="xp-title">{T.human[0]}<br/><em>{T.human[1]}</em></h2><p>{T.human[2]}</p><ExperienceLink go={go} route="about" secondary>{T.human[3]}</ExperienceLink></div></div></section><ExperienceClose go={go}/></div>;
}
export function AboutOpening({go}) {return <><section className="xp-hero xp-hero--about"><div className="xp-wrap xp-hero__grid"><div className="xp-hero__copy"><p className="xp-kicker">{T.about[0]}</p><h1 className="xp-title">{T.about[1]}<br/><em>{T.about[2]}</em></h1><p className="xp-lede">{T.about[3]}</p><ExperienceLink go={go} route="about" anchor="wir-team">{T.about[4]}</ExperienceLink></div><div className="xp-portrait-scene"><LightThreads/>{[['nicholas','Nicholas Weiser','CEO'],['jose-carlos','José Carlos de Paula','CSO']].map(([file,name,role],i)=><figure key={file} style={{'--i':i}}><img src={'/assets/team/'+file+'.jpg'} alt={name} width="480" height="620"/><figcaption><b>{name}</b><span>{role} · Co-Founder</span></figcaption></figure>)}</div></div></section><section className="xp-belief"><div className="xp-wrap"><h2 className="xp-title">{T.belief[0]}<br/><em>{T.belief[1]}</em></h2><div><p>{T.belief[2]}</p><div className="xp-belief__orbit">{T.belief.slice(3).map(x=><span key={x}>{x}</span>)}</div></div></div></section></>;}
